config/routes.rb
Rails.application.routes.draw do
  # get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post

    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_comment_counters

  private

  def update_comment_counters
    post.update(comment_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :user
  belongs_to :post

  after_save :update_likes

  private

  def update_likes
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true, length: { maximum: 1000 }

  after_save :update_posts_counter

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :bio, :photo, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :bio, :photo, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(@post.author, @post)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @post.decrement!(:comment_counter)
    @comment.destroy!
    redirect_to user_post_path(author_id: @post.author_id, id: @post.id), notice: 'Comment successfully deleted'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include LikesHelper

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(like_params)
    @like.user = current_user

    if @like.save
      redirect_to user_post_path(@post.author, @post), notice: 'Liked the post!'
    else
      redirect_to user_post_path(@post.author, @post), alert: 'Failed to like the post.'
    end
  end

  private

  def like_params
    params.require(:like).permit(:author_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_posts_path(current_user, @post)
    else
      render :new
    end
  end

  def destroy
    @post = Post.includes(:likes).find(params[:id])
    @author = @post.author
    @author.decrement!(:posts_counter)
    @post.likes.destroy_all
    @post.destroy!

    redirect_to user_posts_path(id: @author.id), notice: 'Post successfully deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_button_text(post, user)
    if post.likes.exists?(author: user)
      'Unlike'
    else
      "<i class='far fa-thumbs-up'></i> Like".html_safe
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="new-comment">
    <h1>comment</h1>
    <%= form_with model: @comment, url: user_post_comments_path do |form| %>
    <div class="text-container">
        <%= form.label :text%>
        <%= form.text_area :text, cols: 30, rows:10%><br>
    </div>
    
        <div class="btn-container">
            <%= form.submit "Submit", class:"btn" %>
        <%= link_to 'Back to post', user_post_path(@post.author, @post), class: 'back-btn' %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "user", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "user_show", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "post", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "post_show", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "sign_up", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts-container">
    <div class="header">
        <%= render partial: 'shared/user_card', locals: {user: @user} %>
    </div>
    <div class="posts">
      <% @posts.each do |post| %>
        <%= link_to user_post_path(user_id: post.author.id, id: post.id), class: 'post-item' do %>
        <%= render partial: 'shared/post_card', locals: {post: post} %>
      <% end %>
        <div class="comments-container">
            <% if post.comments.empty? %>
              <p>no comments</p>
            <% end %>
            <% post.recent_comments.each do |comment| %>
              <p>
                <%= comment.author.name %>: <%= comment.text %>
              </p>
            <% end %>
        </div>
        <% end %>
    </div>

    <div class="new-post">
        <%= link_to 'Create post', new_user_post_path, class: 'btn' %>
    </div>

    <div class="pagination">
      <ul class="pagination">
        <li>paginate</li>
      </ul>
    </div>
    
</div>

app/views/posts/new.html.erb
    <div class="post-form">
        <%= form_with model: @post, url: user_posts_path, class: 'form_container' do |form| %>
            <div class='form'>
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: 'Greatest in the world' %>
            </div>

            <div class='form_group'>
            <%= form.label :text %>
            <%= form.text_area :text, placeholder: 'What do you have in mind' %>
            </div>

            <%= form.submit 'Add post', class: 'submit-btn' %>
            <%# <%= link_to 'Back to posts', user_posts_path, class: 'back_btn' %> 
        <% end %>
    </div>

app/views/posts/show.html.erb
<div class="post-details">
    <div class="log-out-cont">
            <%if can? :destroy, @post%>
                <%= button_to 'Delete', user_post_path(user_id: @post.author_id, id: @post.id), method: :delete, data: {confirm: 'Are you sure you want to delete this post ?'}, class: 'log-out-button' %>
            <%end%>
    </div><br/>

    <div class="post-info">
        <div class="post-header">
            <h3>
                <%= @post.title %>
                by:
                <%= @post.author.name %>
            </h3>
            <div class="post-int">
                <p>Comments:
                    <%= @post.comment_counter || 0 %>
                </p>
                <p>Likes:
                    <%= @post.likes_counter || 0 %>
                </p>
            </div>
        </div>
        <div class="post-text">
            <p>
                <%= @post.text %>
            </p>
        </div>
    </div>
    <div class="comments-container">
        <div class="comments">
            <% if @post.comments.empty? %>
            <p>no comments</p>
            <% end %>
            <% @post.recent_comments.each do |comment| %>
            <p>
                <%= comment.author.name %>: <%= comment.text %>
            </p>
            <div class="log-out-cont">
                <% if can? :destroy, comment %>
                    <%= button_to 'Delete', user_post_comment_path(author_id: comment.author_id, post_id: comment.post_id, id: comment.id), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' }, class: 'log-out-button' %>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>

    <div class="btn-container">
        <%= link_to 'Comment', new_user_post_comment_path(@user, @post), class: 'btn' %>
        <%= form_for(@post.likes.new, url: user_post_likes_path(@post.author, @post)) do |f| %>
            <%= f.hidden_field :author_id, value: current_user.id %>
            <%= button_to like_button_text(@post, @user), user_post_likes_path(@user, @post), method: :post, class: 'btn' %>
        <% end %>
    </div>
</div>

app/views/shared/_comment_card.html.erb
<div class="comment-card">
    <div class="card-body">
        <% comments.each do |comment| %>
            <p><span class="author-name"><%= comment.author.name %></span>: <span class="comment-text"><%= comment.text %></span></p>
        <% end %>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_post_card.html.erb
<div class="post-card">
    <div class="post-title">
        <h3>
            <%= post.title%>
        </h3>
    </div>
    <div class="post-text">
        <p>
            <%= post.text%>
        </p>
    </div>
    <div class="interaction">
        <div class="likes">
            <span class="heart">
                <i class="fa-regular fa-heart"></i>
            </span>
            <span class="likes-count">
                <%= post.likes_counter || 0 %>
            </span>
        </div>
        <div class="comments">
            <span class="comment">
                <i class="fa-regular fa-comment"></i>
            </span>
            <span class="comments-count">
                <%= post.comment_counter || 0 %>
            </span>
        </div>
    </div>
</div>

app/views/shared/_user_card.html.erb
<div class="user-card">
    <div class="user-image">
        <img src="<%= user.photo %>" alt="<%= user.name %>">
    </div>
    <div class="user-content">
        <div class="name">
            <h3>
                <%= user.name %>
            </h3>
        </div>
        <div class="num-posts">
            <span>
               number of posts: <%= user.posts_counter %> posts
            </span>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="user-container">
<div class="log-out-cont">
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "log-out-button" %>
</div>
    <%if @users.empty?%>
        <h1>There are no users yet</h1>
    <%end%>
    <%@users.each do |user|%>
        <a href="/users/<%= user.id%>">
            <%= render partial: 'shared/user_card', locals: {user: user} %>
        </a>
    <%end%>
</div>

app/views/users/show.html.erb
<div class="user-profile">
    <div class="header">
        <%= render 'shared/user_card', user: @user %>
    </div>

    <div class="user-bio">
        <h3>Bio</h3>
        <p><%= @user.bio %></p>
    </div>

    <div class="recent-posts">
        <h3 class="rp">Recent Posts</h3>
        <% if @user.recent_posts.present? %>
            <% @user.recent_posts.each do |post| %>
                <%= link_to user_post_path(user_id: post.author.id, id: post.id), class: 'post-item' do %>
                    <%= render 'shared/post_card', post: post %>
                <% end %>
            <% end %>
        <% end %>
    </div>

    <div class="all-posts">
            <%= link_to "See All Posts", user_posts_path(user_id: @user.id), class: 'btn-post'%>
    </div>
</div>